---
title: "Lab experiment"
author: "Erik Ø. Sørensen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(targets)
library(tidyverse)
library(gt)
library(modelsummary)
library(scales)
library(patchwork)
library(fixest)
```


# Replication of main results: lab experiment
```{r replication of main, echo=FALSE}
tar_load(lab_treatments)
qm <- c("treatmentfWTA-No Choice"="WTA-No Choice",
        "treatmentfWTA-No Exp" = "WTA-No Exp.",
        "competition"="WTA Competition",
        "winning_margin"="Winning margin",
        "(Intercept)" = "Constant")
tc1 <-  modelsummary(lab_treatments, 
                     coef_map=qm,
                     stars = c('*' = .1, '**' = .05, '***'=.01),
                     gof_map = c("nobs", "r.squared"),
                     output = "gt",
                     standalone = FALSE) |>
    tab_spanner(label="All to winner", columns=2:4) |>
    tab_spanner(label="Share to winner", columns=5:7)
tc1
gtsave(tc1,"tables/LAB_replication.tex")
```

