---
title: "Lab experiment"
author: "Erik Ø. Sørensen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(targets)
library(tidyverse)
library(gt)
library(modelsummary)
library(scales)
library(patchwork)
library(fixest)
```


# Labelling of treatments.

In the data from theoriginal lab experiment in 2014, the labelling of 
treatments is slightly different: 

| 2014 label  | 2018, 2025 label |
|-------------|------------------|
| 1:full info | WTA-No Choice    |
| 2:choice    | WTA              |
| 3:no info   | WTA-No Expectations |
| 4:luck      | Luck             |


# Balance table

```{r balance, echo=FALSE}
tar_load(lab_balance)
btable <- lab_balance |> gt() |>
  fmt_number(decimals=3, rows=1:3) |>
  fmt_number(decimals=1, rows=1, columns = 2:6) |>
  tab_spanner(label="Winner-Take-All Treatments", columns=3:5)
btable
btable |> gtsave(here::here("tables","LAB_balance.tex"))
```


# Replication of main results: lab experiment
```{r replication of main, echo=FALSE}
tar_load(lab_treatments)
qm <- c("treatmentfWTA-No Choice"="WTA-No Choice",
        "treatmentfWTA-No Exp" = "WTA-No Exp.",
        "competition"="WTA Competition",
        "winning_margin"="Winning margin",
        "(Intercept)" = "Constant")
tc1 <-  modelsummary(lab_treatments, 
                     coef_map=qm,
                     stars = c('*' = .1, '**' = .05, '***'=.01),
                     gof_map = c("nobs", "r.squared"),
                     output = "gt",
                     standalone = FALSE) |>
    tab_spanner(label="All to winner", columns=2:4) |>
    tab_spanner(label="Share to winner", columns=5:7)
tc1
gtsave(tc1,"tables/LAB_replication.tex")
```

# What about the equal performance case?

```{r}
tar_load(mmw2014)
equal_performance <- mmw2014 |> 
  filter(e1==e2) |>
  mutate(equality = y1==y2) 
table(equal_performance$equality)
equal_performance |> 
  filter(equality==FALSE) |>
  select(c(T,x1,x2,e1,e2,y1,y2)) |> gt()
```

